name: 'cryptobookkeeper'
version: '0.1.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'cryptobookkeeper'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  cryptobookkeeper:
    # Curated models use incremental materialization for efficiency
    curated:
      +materialized: incremental
      +unique_key: txid
      +on_schema_change: sync_all_columns

# Configuring data tests (new syntax)
# Full documentation: https://docs.getdbt.com/docs/build/data-tests
data_tests:
  cryptobookkeeper:
    +store_failures: true
