version: 2

models:
  - name: tx_unified
    description: "Unified transaction model combining all sources (exchange + on-chain)"
    columns:
      - name: txid
        description: "Unique transaction identifier"
        data_tests:
          - not_null
          - unique
      - name: ts_utc
        description: "Transaction timestamp in UTC"
        data_tests:
          - not_null
      - name: amount
        description: "Transaction amount"
        data_tests:
          - not_null
      - name: domain
        description: "Data source domain (exchange/onchain)"
        data_tests:
          - not_null
          - accepted_values:
              values: ['exchange', 'onchain']
      - name: source
        description: "Specific data source (e.g., coinbase_trades, debank_eth)"
        data_tests:
          - not_null
