version: 2

sources:
  - name: raw
    description: "Raw data tables from DuckDB"
    tables:
      - name: exchanges_trades
        description: "Raw exchange trade data"
        columns:
          - name: txid
            description: "Unique transaction identifier"
            data_tests:
              - not_null
              - unique
          - name: datetime
            description: "Transaction timestamp in UTC"
            data_tests:
              - not_null
          - name: amount
            description: "Transaction amount"
            data_tests:
              - not_null
      
      - name: exchanges_deposits
        description: "Raw exchange deposit data"
        columns:
          - name: txid
            description: "Unique transaction identifier"
            data_tests:
              - not_null
              - unique
          - name: datetime
            description: "Transaction timestamp in UTC"
            data_tests:
              - not_null
          - name: amount
            description: "Transaction amount"
            data_tests:
              - not_null
      
      - name: exchanges_withdrawals
        description: "Raw exchange withdrawal data"
        columns:
          - name: txid
            description: "Unique transaction identifier"
            data_tests:
              - not_null
              - unique
          - name: datetime
            description: "Transaction timestamp in UTC"
            data_tests:
              - not_null
          - name: amount
            description: "Transaction amount"
            data_tests:
              - not_null
      
      - name: onchain_transfers
        description: "Raw on-chain token transfer data"
        columns:
          - name: tx_hash
            description: "Blockchain transaction hash"
            data_tests:
              - not_null
          - name: from_address
            description: "Sender address"
            data_tests:
              - not_null
          - name: to_address
            description: "Recipient address"
            data_tests:
              - not_null
          - name: value
            description: "Transfer value"
            data_tests:
              - not_null
